### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module './_baseClone'

### ISSUE THREAD

**Issue by valnaumov** [fusepilot/parcel-plugin-cep-starter#3]
Hi. I am getting the following error when running the build.

```
> yarn run start
yarn run v1.9.4
$ concurrently "yarn run start-js" "yarn run start-jsx"
$ parcel watch src/jsx/index.jsx.ts --no-hmr --no-source-maps
$ parcel src/js/index.html
[0] (node:2352) UnhandledPromiseRejectionWarning: Error: Cannot find module './_baseClone'
[0]     at Function.Module._resolveFilename (module.js:547:15)
[0]     at Function.Module._load (module.js:474:25)
[0]     at Module.require (module.js:596:17)
[0]     at require (c:\projects\parcel-cep-project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[0]     at Object.<anonymous> (c:\projects\parcel-cep-project\node_modules\lodash\cloneDeep.js:1:79)
[0]     at Module._compile (c:\projects\parcel-cep-project\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
[0]     at Object.Module._extensions..js (module.js:663:10)
[0]     at Module.load (module.js:565:32)
[0]     at tryModuleLoad (module.js:505:12)
[0]     at Function.Module._load (module.js:497:3)
[1] (node:8884) UnhandledPromiseRejectionWarning: Error: Cannot find module './_baseClone'
[1]     at Function.Module._resolveFilename (module.js:547:15)
[1]     at Function.Module._load (module.js:474:25)
[1]     at Module.require (module.js:596:17)
[1]     at require (c:\projects\parcel-cep-project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[1]     at Object.<anonymous> (c:\projects\parcel-cep-project\node_modules\lodash\cloneDeep.js:1:79)
[1]     at Module._compile (c:\projects\parcel-cep-project\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
[1]     at Object.Module._extensions..js (module.js:663:10)
[1]     at Module.load (module.js:565:32)
[1]     at tryModuleLoad (module.js:505:12)
[1]     at Function.Module._load (module.js:497:3)
[1] (node:8884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:8884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] (node:2352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:2352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] yarn run start-jsx exited with code 0
[0] yarn run start-js exited with code 0
Done in 1.83s.
```

Any clue?

**Comment by valnaumov** [comment]
I've managed to get it working when installed with npm, however the extension is not shown under Window/Extension menu. Is there something to do?
